<script lang="ts">
  import { lang } from '$lib/stores/lang';

  const UPDATED = '08/06/2026';

  const t = {
    meta: {
      title: { pt: 'Política de Cookies — Crianex Hub', en: 'Cookie Policy — Crianex Hub' },
      desc: {
        pt: 'Como a Crianex utiliza cookies e tecnologias similares, e quais são seus direitos conforme a LGPD.',
        en: 'How Crianex uses cookies and similar technologies, and your rights under LGPD.',
      },
    },
    eyebrow: { pt: 'Legal & Privacidade', en: 'Legal & Privacy' },
    h1: { pt: 'Política de Cookies.', en: 'Cookie Policy.' },
    lede: {
      pt: 'Este documento explica como o Crianex Hub utiliza cookies e tecnologias similares de armazenamento local, em conformidade com a Lei Geral de Proteção de Dados (Lei 13.709/2018 — LGPD) e demais normas aplicáveis.',
      en: "This document explains how Crianex Hub uses cookies and similar local storage technologies, in accordance with Brazil's General Data Protection Law (Lei 13.709/2018 — LGPD) and other applicable regulations.",
    },
    updated: { pt: 'Última atualização', en: 'Last updated' },
    sections: [
      {
        n: '01',
        title: { pt: 'O que são cookies', en: 'What are cookies' },
        body: {
          pt: 'Cookies são pequenos arquivos de texto armazenados no seu navegador quando você visita um site. Eles permitem que o site reconheça seu dispositivo em visitas futuras e mantenha preferências como idioma selecionado. Sob a LGPD (Art. 5º, I), dados gerados por cookies que permitam identificar um usuário são considerados dados pessoais e estão sujeitos à mesma proteção.',
          en: 'Cookies are small text files stored in your browser when you visit a website. They allow the site to recognize your device on future visits and retain preferences such as selected language. Under LGPD (Art. 5, I), data generated by cookies that may identify a user is considered personal data and is subject to the same protections.',
        },
      },
      {
        n: '02',
        title: { pt: 'Cookies que utilizamos', en: 'Cookies we use' },
        body: {
          pt: 'Utilizamos exclusivamente cookies funcionais e de sessão: (a) cookie_consent — armazena sua escolha de consentimento (aceitar/recusar), retido por até 12 meses no localStorage do navegador; (b) cookies de sessão de autenticação, criados apenas quando você acessa áreas restritas do painel administrativo e excluídos automaticamente ao fechar o navegador. Não utilizamos cookies de rastreamento, publicidade ou análise de comportamento de terceiros.',
          en: 'We use exclusively functional and session cookies: (a) cookie_consent — stores your consent choice (accept/decline), retained for up to 12 months in the browser localStorage; (b) authentication session cookies, created only when you access restricted areas of the admin panel and automatically deleted when you close the browser. We do not use third-party tracking, advertising, or behavioral analytics cookies.',
        },
      },
      {
        n: '03',
        title: { pt: 'Base legal (LGPD)', en: 'Legal basis (LGPD)' },
        body: {
          pt: 'O tratamento de dados via cookies se apoia em duas bases legais previstas no Art. 7º da LGPD: (i) consentimento explícito do titular (inciso I), coletado pelo banner exibido na primeira visita; (ii) legítimo interesse do controlador (inciso IX) para cookies estritamente necessários ao funcionamento da autenticação, que não requerem consentimento por serem indispensáveis ao serviço contratado. O consentimento pode ser revogado a qualquer momento através das configurações do navegador ou pelo e-mail contato@crianex.com.',
          en: "The processing of data via cookies relies on two legal bases under LGPD Art. 7: (i) the data subject's explicit consent (item I), collected by the banner displayed on the first visit; (ii) the controller's legitimate interest (item IX) for strictly necessary authentication cookies, which do not require consent as they are essential to the contracted service. Consent may be withdrawn at any time through browser settings or by emailing contato@crianex.com.",
        },
      },
      {
        n: '04',
        title: { pt: 'Cookies de terceiros', en: 'Third-party cookies' },
        body: {
          pt: 'O Crianex Hub não carrega scripts de redes sociais, plataformas de publicidade ou ferramentas de analytics de terceiros nas páginas públicas da vitrine. Caso isso mude, esta política será atualizada antes da implementação e uma nova solicitação de consentimento será exibida.',
          en: 'Crianex Hub does not load social network scripts, advertising platforms, or third-party analytics tools on the public vitrine pages. Should this change, this policy will be updated before implementation and a new consent request will be displayed.',
        },
      },
      {
        n: '05',
        title: { pt: 'Como gerenciar cookies', en: 'How to manage cookies' },
        body: {
          pt: 'Você pode controlar e excluir cookies diretamente no seu navegador: Chrome → Configurações → Privacidade → Cookies; Firefox → Preferências → Privacidade e Segurança; Safari → Preferências → Privacidade. Ao recusar ou excluir cookies, algumas funcionalidades do site podem ser afetadas, como a manutenção do idioma selecionado.',
          en: 'You can control and delete cookies directly in your browser: Chrome → Settings → Privacy → Cookies; Firefox → Preferences → Privacy & Security; Safari → Preferences → Privacy. Refusing or deleting cookies may affect some site functionality, such as retaining the selected language.',
        },
      },
      {
        n: '06',
        title: { pt: 'Seus direitos (Art. 18 LGPD)', en: 'Your rights (Art. 18 LGPD)' },
        body: {
          pt: 'Em relação ao tratamento de dados via cookies, você pode: confirmar a existência do tratamento; acessar os dados gerados; solicitar a exclusão dos dados coletados com base em consentimento; e revogar o consentimento previamente concedido. Para exercer qualquer direito, envie um e-mail para contato@crianex.com com o assunto "Direitos LGPD — Cookies".',
          en: 'Regarding cookie-based data processing, you may: confirm the existence of processing; access the data collected; request deletion of data collected based on consent; and withdraw previously granted consent. To exercise any right, email contato@crianex.com with the subject "LGPD Rights — Cookies".',
        },
      },
      {
        n: '07',
        title: { pt: 'Alterações nesta política', en: 'Changes to this policy' },
        body: {
          pt: 'Esta política pode ser atualizada para refletir mudanças nos cookies utilizados ou na legislação aplicável. A data de última atualização indicada no topo deste documento reflete sempre a versão vigente. Se introduzirmos novos tipos de cookies, exibiremos um novo banner de consentimento antes de ativá-los.',
          en: 'This policy may be updated to reflect changes in the cookies used or applicable legislation. The last updated date shown at the top always reflects the current version. If we introduce new types of cookies, we will display a new consent banner before activating them.',
        },
      },
    ],
  };
</script>

<svelte:head>
  <title>{t.meta.title[$lang]}</title>
  <meta name="description" content={t.meta.desc[$lang]} />
</svelte:head>

<div class="cookies-page">
  <section class="cookies-hero">
    <a href="/contato" class="back-link">
      <svg
        width="14"
        height="14"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
        aria-hidden="true"
        style="transform: rotate(180deg)"
      >
        <path d="M5 12h14M12 5l7 7-7 7" />
      </svg>
      {$lang === 'pt' ? 'Voltar ao contato' : 'Back to contact'}
    </a>
    <div class="eyebrow">
      <span class="dot"></span>
      {t.eyebrow[$lang]}
    </div>
    <h1>{t.h1[$lang]}</h1>
    <p class="lede">{t.lede[$lang]}</p>
    <div class="meta-row">
      <span class="mono">{t.updated[$lang]}: {UPDATED}</span>
      <span class="pill">LGPD — Lei 13.709/2018</span>
    </div>
  </section>

  <section class="cookies-body">
    <div class="sections-grid">
      {#each t.sections as s, i}
        <div
          class="policy-section"
          class:full={i === t.sections.length - 1 && t.sections.length % 2 !== 0}
        >
          <div class="section-n mono">{s.n}</div>
          <h3>{s.title[$lang]}</h3>
          <p>{s.body[$lang]}</p>
        </div>
      {/each}
    </div>

    <div class="contact-card">
      <div class="card-icon">
        <svg
          width="20"
          height="20"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="1.8"
          stroke-linecap="round"
          stroke-linejoin="round"
          aria-hidden="true"
        >
          <path d="M12 22C6.477 22 2 17.523 2 12S6.477 2 12 2s10 4.477 10 10-4.477 10-10 10z" />
          <path d="M12 16v-4M12 8h.01" />
        </svg>
      </div>
      <div>
        <p class="card-title">
          {$lang === 'pt'
            ? 'Dúvidas sobre cookies ou privacidade?'
            : 'Questions about cookies or privacy?'}
        </p>
        <p class="card-body">
          {$lang === 'pt'
            ? 'Entre em contato com nosso encarregado de dados (DPO).'
            : 'Contact our Data Protection Officer (DPO).'}
        </p>
      </div>
      <a href="mailto:contato@crianex.com" class="btn ghost sm"> contato@crianex.com </a>
    </div>

    <div class="also-read">
      <a href="/privacidade" class="also-link">
        <svg
          width="14"
          height="14"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
          aria-hidden="true"
        >
          <path d="M5 12h14M12 5l7 7-7 7" />
        </svg>
        {$lang === 'pt' ? 'Ver também: Política de Privacidade' : 'See also: Privacy Policy'}
      </a>
    </div>
  </section>
</div>

<style>
  .cookies-page {
    --bg-elev: #ffffff;
    --bg: #fcfcfc;
    --line: #e8e6e2;
    --text-muted: #6b6862;
    --text-faint: #9a968e;
    --accent-soft: rgba(127, 63, 229, 0.08);
    --r-lg: 18px;
  }

  .cookies-hero {
    padding: 48px 40px 20px;
    border-bottom: 1px solid var(--line);
    max-width: 1200px;
    margin: 0 auto;
  }

  .back-link {
    display: flex;
    align-items: center;
    gap: 6px;
    font-size: 13px;
    color: var(--text-muted);
    text-decoration: none;
    margin-bottom: 20px;
    transition: color 0.15s;
  }

  .back-link:hover {
    color: var(--venom);
  }

  .eyebrow {
    font-family: var(--font-mono);
    font-size: 11px;
    letter-spacing: 0.08em;
    text-transform: uppercase;
    color: var(--text-muted);
    display: inline-flex;
    align-items: center;
    gap: 8px;
    margin-bottom: 5px;
  }

  .dot {
    width: 6px;
    height: 6px;
    border-radius: 50%;
    background: var(--purple);
    flex-shrink: 0;
  }

  h1 {
    font-size: clamp(36px, 5vw, 56px);
    font-weight: 600;
    letter-spacing: -0.035em;
    line-height: 1;
    color: var(--venom);
    margin: 0 0 20px;
  }

  .lede {
    color: var(--text-muted);
    font-size: 16px;
    line-height: 1.6;
    max-width: 64ch;
    margin: 0 0 20px;
  }

  .meta-row {
    display: flex;
    align-items: center;
    gap: 16px;
    flex-wrap: wrap;
  }

  .mono {
    font-family: var(--font-mono);
    font-size: 11px;
    color: var(--text-faint);
    letter-spacing: 0.06em;
  }

  .pill {
    font-family: var(--font-mono);
    font-size: 10px;
    letter-spacing: 0.06em;
    text-transform: uppercase;
    color: var(--purple);
    background: var(--accent-soft);
    border: 1px solid rgba(127, 63, 229, 0.2);
    border-radius: 100px;
    padding: 3px 10px;
  }

  .cookies-body {
    padding: 0 0 64px;
    max-width: 1200px;
    margin: 0 auto;
  }

  .sections-grid {
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    gap: 0;
    border-top: 1px solid var(--line);
    border-left: 1px solid var(--line);
    margin-bottom: 32px;
  }

  .policy-section {
    padding: 28px 32px;
    border-right: 1px solid var(--line);
    border-bottom: 1px solid var(--line);
    display: flex;
    flex-direction: column;
    gap: 10px;
  }

  .policy-section.full {
    grid-column: span 2;
  }

  .section-n {
    font-size: 11px;
    color: var(--text-faint);
    letter-spacing: 0.08em;
  }

  .policy-section h3 {
    font-size: 16px;
    font-weight: 500;
    letter-spacing: -0.02em;
    color: var(--venom);
    margin: 0;
  }

  .policy-section p {
    color: var(--text-muted);
    font-size: 14px;
    line-height: 1.65;
    margin: 0;
  }

  .contact-card {
    background: var(--bg-elev);
    border: 1px solid var(--line);
    border-radius: var(--r-lg);
    padding: 28px 32px;
    display: flex;
    align-items: center;
    gap: 20px;
    flex-wrap: wrap;
    margin: 0 40px 20px;
  }

  .card-icon {
    width: 44px;
    height: 44px;
    border-radius: 10px;
    background: var(--accent-soft);
    color: var(--purple);
    display: grid;
    place-items: center;
    flex-shrink: 0;
  }

  .contact-card > div {
    flex: 1;
    min-width: 0;
  }

  .card-title {
    font-size: 15px;
    font-weight: 500;
    color: var(--venom);
    margin: 0 0 4px;
  }

  .card-body {
    font-size: 13px;
    color: var(--text-muted);
    margin: 0;
  }

  .btn {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    padding: 10px 20px;
    border-radius: 8px;
    font-family: inherit;
    font-size: 13px;
    font-weight: 500;
    cursor: pointer;
    transition: opacity 0.15s;
    text-decoration: none;
    white-space: nowrap;
  }

  .btn.ghost {
    background: transparent;
    border: 1px solid var(--line);
    color: var(--venom);
  }

  .btn.ghost:hover {
    border-color: var(--text-muted);
    opacity: 0.8;
  }

  .also-read {
    padding: 0 40px;
  }

  .also-link {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    font-size: 13px;
    color: var(--text-muted);
    text-decoration: none;
    transition: color 0.15s;
  }

  .also-link:hover {
    color: var(--venom);
  }

  @media (max-width: 768px) {
    .cookies-hero {
      padding: 32px 20px 28px;
    }

    .cookies-body {
      padding: 0 0 48px;
    }

    .sections-grid {
      grid-template-columns: 1fr;
    }

    .policy-section.full {
      grid-column: span 1;
    }

    .policy-section {
      padding: 22px 20px;
    }

    .contact-card {
      flex-direction: column;
      align-items: flex-start;
      padding: 20px;
      margin: 0 20px 20px;
    }

    .btn.ghost {
      align-self: stretch;
      justify-content: center;
    }

    .also-read {
      padding: 0 20px;
    }
  }
</style>
